Update quantum control, simulators and experiment control libraries
qosf/awesome-quantum-software pull request #57
Opened 2021-03-15 08:31 UTC by lazyoracle

2021-03-15 18:19 UTC, markf94 requested changes
This is amazing! Thanks for all these new software packages @lazyoracle! I only had the one comment below

2021-03-15 18:19 UTC, markf94 commented on README.md
> +## Quantum Control
Could you please sort this category by programming language such that it follows the same pattern as the other sections?

2021-03-17 13:30 UTC, lazyoracle commented
I have updated the sub categories. Let me know if any other changes are required @markf94

2021-03-19 22:50 UTC, merged

2021-03-19 22:51 UTC, markf94 commented
Great thanks!